apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-function-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: js-function-operator
  template:
    metadata:
      labels:
        name: js-function-operator
    spec:
      serviceAccountName: js-function-operator
      containers:
        - name: js-function-operator
          # Replace this with the built image name
          image: quay.io/lanceball/js-function-operator:v0.0.1
          command:
          - js-function-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "js-function-operator"
